apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd

spec:
  project: default
  source:
    repoURL: git@github.com:yessine99/Homelab.git
    path: infra/k8s/app
    targetRevision: staging
    helm:
      valueFiles:
        - values/staging.yml
        - values/prod.yml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
