apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:yessine99/Homelab.git
    path: infra/k8s/chart
    targetRevision: staging
    helm:
      valueFiles:
        - values/staging.yml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: staging




