apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth
  namespace: {{ .Values.namespace }}

spec:
  revisionHistoryLimit: 1

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
        - name: auth
          image: {{ .Values.auth.image }}:{{ .Values.auth.tag }}
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: auth
          env:
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: jwt-access-secret

            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: jwt-refresh-secret

          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"

          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 6

          readinessProbe:
            httpGet:
              path: /readyz
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 1
          
