apiVersion: v1
kind: Secret

metadata:
  name: auth
  namespace: {{ .Values.namespace }}

type: Opaque
data:
  jwt-access-secret: bXlfYWNjZXNz
  jwt-refresh-secret: bXlfcmVmcmVzaA==

# kubectl create secret generic auth \
#   --from-literal=jwt-access-secret='access_secret' \
#   --from-literal=jwt-refresh-secret='refresh_secret' \
#   -n staging
