apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: deny-all-ingress
  namespace: {{ .Values.namespace }}
  
spec:
  podSelector: {}
  policyTypes:
  - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: allow-ingress-from-ingress-nginx
  namespace: {{ .Values.namespace }}

spec:
  podSelector:
    matchExpressions:
      - {key: app, operator: In, values: [client, auth]}

  policyTypes:
  - Ingress

  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-nginx

        podSelector:
          matchLabels:
            app.kubernetes.io/component: controller 
            app.kubernetes.io/name: ingress-nginx