helm:
  parameters:
  - name: image.name
    value: yessinerekik/client
    forcestring: true
  - name: image.tag
    value: dev@sha256:5a49f51af0d44ced93ec581b44d5430a794707038438f1ba8474e54dd6227258
    forcestring: true
  - name: yessinerekik/client:dev
    value: yessinerekik/client@sha256:99d286f4fb3cc19374dba0d055b643252ef437fef987eecce570cdc369488140
    forcestring: true
