apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.Values.name}}
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: client={{ .Values.images }}
    argocd-image-updater.argoproj.io/client.update-strategy: digest

spec:
  project: default
  source:
    repoURL: git@github.com:yessine99/Homelab.git
    path: infra/k8s/chart
    targetRevision: {{.Values.branch}}
    helm:
      valueFiles:
        - {{.Values.valueFiles}}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{.Values.destination.namespace}}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
