apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-overriden-datasources
  namespace: monitoring
  labels:
    grafana_datasource: '1'

data:
  override-datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://prometheus-kube-prometheus-prometheus.monitoring:9090/
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        
    - name: Alertmanager
      type: alertmanager
      uid: alertmanager
      url: http://prometheus-kube-prometheus-alertmanager.monitoring:9093/
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus

    - name: Loki
      type: loki
      uid: loki
      url: "http://loki:3100"
      access: proxy
      jsonData: 
        {}