################### Deployment ###################
apiVersion: apps/v1
kind: Deployment

metadata:
  name: client
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: client

  template:
    metadata:
      labels:
        app: client

    spec:
      containers:
        - name: client
          image: {{ .Values.client.image.name }}:{{ .Values.client.image.tag }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: client

          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"

---
################### Service ###################
apiVersion: v1
kind: Service

metadata:
  name: client
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: client
  ports:
    - port: 3000
      targetPort: 3000

---
################### ConfigMap ###################
apiVersion: v1
kind: ConfigMap

metadata:
  name: client
  namespace: {{ .Values.namespace }}

data:
  NEXT_PUBLIC_ENV: {{ .Values.namespace }}
