################### Deployment ###################
apiVersion: apps/v1
kind: Deployment

metadata:
  name: client
  namespace: {{ .Values.namespace }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: client

  template:
    metadata:
      labels:
        app: client

    spec:
      containers:
        - name: client
          image: yessinerekik/client:staging-ba115df29f2c0d99bc6127f937875caa513cebc8 # change me in the pipeline
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: client

          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

---
################### Service ###################
apiVersion: v1
kind: Service

metadata:
  name: client
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: client
  ports:
    - port: 3000
      targetPort: 3000

---
################### ConfigMap ###################
apiVersion: v1
kind: ConfigMap

metadata:
  name: client
  namespace: {{ .Values.namespace }}

data:
  NEXT_PUBLIC_ENV: {{ .Values.namespace }}
