apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.Values.name}}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  
  annotations:
    argocd-image-updater.argoproj.io/image-list: {{ .Values.images }}
    argocd-image-updater.argoproj.io/client.helm.image-name: client.image
    argocd-image-updater.argoproj.io/client.helm.image-tag: client.tag
    argocd-image-updater.argoproj.io/auth.helm.image-name: auth.image
    argocd-image-updater.argoproj.io/auth.helm.image-tag: auth.tag

    #argocd-image-updater.argoproj.io/write-back-method: git # default argocd
    argocd-image-updater.argoproj.io/update-strategy: digest

spec:
  project: default
  source:
    repoURL: git@github.com:yessine99/Homelab.git
    path: infra/k8s/charts/services
    targetRevision: {{.Values.branch}}
    helm:
      valueFiles:
        - {{.Values.valueFiles}}

  destination:
    server: "https://kubernetes.default.svc"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
