name: Auth Service Pipeline

on:
  push:
    paths:
      - 'auth-service/**'
  pull_request:
    paths:
      - 'auth-service/**'

jobs:
  call-reusable-pipeline:
    uses: ./.github/workflows/reusable-pipeline.yml
    with:
      service-folder: 'auth-service'
