name: Auth Service Pipeline

on:
  pull_request:
    paths:
      - 'auth-service/**'
  push:
    branches:
      - master
    paths:
      - 'auth-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        if: github.event_name == 'pull_request'
        run: cd auth-service && npm install && npm run test:ci

      - name: Login to Docker Hub, Build and Push Image
        if: github.event_name == 'push'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t yessinerekik/auth-service ./auth-service
          docker push yessinerekik/auth-service
