name: Auth Service Pipeline

on:
  pull_request:
    paths:
      - 'auth-service/**'

  push:
    branches:
      - master
      - staging
    paths:
      - 'auth-service/**'

jobs:
  call-reusable-pipeline:
    uses: ./.github/workflows/reusable-pipeline.yml
    with:
      service-folder: 'auth-service'
    secrets: inherit
