name: Auth Service Pipeline

on:
  pull_request:
    paths:
      - 'auth-service/**'
  push:
    branches:
      - master
    paths:
      - 'auth-service/**'
      - 'auth-service-pipeline.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cd auth-service && npm install

      - name: Run ESLint
        run: cd auth-service && npm run lint

      - name: Run Test Suites
        run: cd auth-service && npm run test:ci

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker Image
        run: docker build -t yessinerekik/auth-service ./auth-service

      - name: Push Docker Image
        run: docker push yessinerekik/auth-service
