name: Storage Service Pipeline

on:
  pull_request:
    paths:
      - 'storage-service/**'
  push:
    branches:
      - master
      - staging
    paths:
      - 'storage-service/**'
      - '.github/workflows/storage-service-pipeline.yml' # for testing deployment convenience

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t test-image ./storage-service

  test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cd storage-service && npm install

      - name: Run ESLint
        run: cd storage-service && npm run lint

      - name: Run Test Suites
        run: cd storage-service && npm run test:ci

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Set IMAGE_TAG
        id: image_tag
        run: echo "IMAGE_TAG=$([[ '${{ github.ref_name }}' == 'master' ]] && echo '${{ github.sha }}' || echo 'staging-${{ github.sha }}')" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t yessinerekik/storage-service:${{ env.IMAGE_TAG }} ./storage-service

      - name: Push Docker Image
        run: docker push yessinerekik/storage-service:${{ env.IMAGE_TAG }}
