name: tests
on:
  pull_request:
    paths:
      - 'auth-service/**' # only execute these jobs when changes are made in this directory
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth-service && npm install && npm run test:ci
